### ISSUE TITLE
how about the accuracy ?

### ISSUE THREAD

**Issue by eivaltsec** [sharmasaravanan/FaceRecognition#1]
did you use lfw test set to validating this demo？how about the accuracy ?thank you.

**Comment by sharmasaravanan** [comment]
yes I have tested this against LFW and FRGC dataset 
for LFW I got 91.5 % accuracy
and for FRGC I got 98.5% accuracy

**Comment by eivaltsec** [comment]
thank you ,i read you code ,but i don't find where is the model ( "./deploy.prototxt", "./FaceRec.caffemodel"),could you push it to your github? just for study,thank you very much!

**Comment by sharmasaravanan** [comment]
Yeah thanks for the updates.
Now i pushed those missing files

**Comment by eivaltsec** [comment]
but i still don't find the caffe model ,deploy.prototxt and FaceRec.caffemodel, and in Makefile line 125 and 128,where is the nbproject/Makefile-impl.mk and nbproject/Makefile-variables.mk,.thank you!
